#ifndef MIRAGE_SIM_ISA_GFX950_INTERPRETER_ARCH_H_
#define MIRAGE_SIM_ISA_GFX950_INTERPRETER_ARCH_H_

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "lib/sim/isa/common/decoded_instruction.h"
#include "lib/sim/isa/common/execution_memory.h"
#include "lib/sim/isa/common/wave_execution_state.h"

namespace mirage::sim::isa {

enum class ProgramRunState {
  kCompleted,
  kBlockedOnBarrier,
};

struct WorkgroupExecutionContext {
  std::span<std::byte> shared_lds{};
  std::uint32_t wave_count = 1;
};

enum class CompiledOpcode : std::uint16_t {
  kSEndpgm,
  kSBarrier,
  kSMovB32,
  kSMovB64,
  kSCmovB32,
  kSCmovB64,
  kSNotB32,
  kSNotB64,
  kSAbsI32,
  kSBrevB32,
  kSBrevB64,
  kSBcnt0I32B32,
  kSBcnt0I32B64,
  kSBcnt1I32B32,
  kSBcnt1I32B64,
  kSFf0I32B32,
  kSFf0I32B64,
  kSFf1I32B32,
  kSFf1I32B64,
  kSFlbitI32B32,
  kSFlbitI32B64,
  kSFlbitI32,
  kSFlbitI32I64,
  kSBitreplicateB64B32,
  kSQuadmaskB32,
  kSQuadmaskB64,
  kSSextI32I8,
  kSSextI32I16,
  kSBitset0B32,
  kSBitset0B64,
  kSBitset1B32,
  kSBitset1B64,
  kSAndSaveexecB64,
  kSAndn1SaveexecB64,
  kSAndn2SaveexecB64,
  kSNandSaveexecB64,
  kSOrn1SaveexecB64,
  kSOrSaveexecB64,
  kSOrn2SaveexecB64,
  kSNorSaveexecB64,
  kSXorSaveexecB64,
  kSXnorSaveexecB64,
  kSAndn1WrexecB64,
  kSAndn2WrexecB64,
  kVNop,
  kVMovB32,
  kVMovB64,
  kVReadfirstlaneB32,
  kVReadlaneB32,
  kVNotB32,
  kVBfrevB32,
  kVFfbhU32,
  kVFfblB32,
  kVFfbhI32,
  kVCvtF16U16,
  kVCvtF16I16,
  kVCvtU16F16,
  kVCvtI16F16,
  kVSatPkU8I16,
  kVCvtF32Ubyte0,
  kVCvtF32Ubyte1,
  kVCvtF32Ubyte2,
  kVCvtF32Ubyte3,
  kVCvtF32I32,
  kVCvtF32U32,
  kVCvtU32F32,
  kVCvtI32F32,
  kVCvtRpiI32F32,
  kVCvtFlrI32F32,
  kVCvtI32F64,
  kVCvtU32F64,
  kVCvtF16F32,
  kVCvtF32F16,
  kVCvtF32F64,
  kVCvtF64F32,
  kVCvtF64I32,
  kVCvtF64U32,
  kVFractF16,
  kVTruncF16,
  kVCeilF16,
  kVRndneF16,
  kVFloorF16,
  kVRcpF16,
  kVSqrtF16,
  kVRsqF16,
  kVLogF16,
  kVExpF16,
  kVSinF16,
  kVCosF16,
  kVFrexpMantF16,
  kVFrexpExpI16F16,
  kVFractF32,
  kVTruncF32,
  kVCeilF32,
  kVRndneF32,
  kVFloorF32,
  kVExpF32,
  kVExpLegacyF32,
  kVLogF32,
  kVLogLegacyF32,
  kVRcpF32,
  kVRcpIflagF32,
  kVRsqF32,
  kVSqrtF32,
  kVSinF32,
  kVCosF32,
  kVFrexpExpI32F32,
  kVFrexpMantF32,
  kVFractF64,
  kVTruncF64,
  kVCeilF64,
  kVRndneF64,
  kVFloorF64,
  kVRcpF64,
  kVRsqF64,
  kVSqrtF64,
  kVFrexpExpI32F64,
  kVFrexpMantF64,
  kVMulLoU32,
  kVMulHiU32,
  kVMulHiI32,
  kVBcntU32B32,
  kVBfmB32,
  kVMbcntLoU32B32,
  kVMbcntHiU32B32,
  kVLshlRevB64,
  kVLshrRevB64,
  kVAshrRevI64,
  kVAdd3U32,
  kVLshlAddU32,
  kVLshlAddU64,
  kVAddLshlU32,
  kVLshlOrB32,
  kVAndOrB32,
  kVOr3B32,
  kVXadU32,
  kVLerpU8,
  kVPermB32,
  kVBfeU32,
  kVBfeI32,
  kVBfiB32,
  kVAlignbitB32,
  kVAlignbyteB32,
  kVMin3I32,
  kVMin3U32,
  kVMax3I32,
  kVMax3U32,
  kVMed3I32,
  kVMed3U32,
  kVSadU8,
  kVSadHiU8,
  kVSadU16,
  kVSadU32,
  kVFmaF32,
  kVFmaF64,
  kVMadI32I24,
  kVMadU32U24,
  kVMadU64U32,
  kVMadI64I32,
  kVCmpFF16,
  kVCmpLtF16,
  kVCmpEqF16,
  kVCmpLeF16,
  kVCmpGtF16,
  kVCmpLgF16,
  kVCmpGeF16,
  kVCmpOF16,
  kVCmpUF16,
  kVCmpNgeF16,
  kVCmpNlgF16,
  kVCmpNgtF16,
  kVCmpNleF16,
  kVCmpNeqF16,
  kVCmpNltF16,
  kVCmpTruF16,
  kVCmpFF32,
  kVCmpLtF32,
  kVCmpEqF32,
  kVCmpLeF32,
  kVCmpGtF32,
  kVCmpLgF32,
  kVCmpGeF32,
  kVCmpOF32,
  kVCmpUF32,
  kVCmpNgeF32,
  kVCmpNlgF32,
  kVCmpNgtF32,
  kVCmpNleF32,
  kVCmpNeqF32,
  kVCmpNltF32,
  kVCmpTruF32,
  kVCmpFF64,
  kVCmpLtF64,
  kVCmpEqF64,
  kVCmpLeF64,
  kVCmpGtF64,
  kVCmpLgF64,
  kVCmpGeF64,
  kVCmpOF64,
  kVCmpUF64,
  kVCmpNgeF64,
  kVCmpNlgF64,
  kVCmpNgtF64,
  kVCmpNleF64,
  kVCmpNeqF64,
  kVCmpNltF64,
  kVCmpTruF64,
  kVCmpClassF16,
  kVCmpClassF32,
  kVCmpClassF64,
  kVCmpxFF16,
  kVCmpxLtF16,
  kVCmpxEqF16,
  kVCmpxLeF16,
  kVCmpxGtF16,
  kVCmpxLgF16,
  kVCmpxGeF16,
  kVCmpxOF16,
  kVCmpxUF16,
  kVCmpxNgeF16,
  kVCmpxNlgF16,
  kVCmpxNgtF16,
  kVCmpxNleF16,
  kVCmpxNeqF16,
  kVCmpxNltF16,
  kVCmpxTruF16,
  kVCmpxFF32,
  kVCmpxLtF32,
  kVCmpxEqF32,
  kVCmpxLeF32,
  kVCmpxGtF32,
  kVCmpxLgF32,
  kVCmpxGeF32,
  kVCmpxOF32,
  kVCmpxUF32,
  kVCmpxNgeF32,
  kVCmpxNlgF32,
  kVCmpxNgtF32,
  kVCmpxNleF32,
  kVCmpxNeqF32,
  kVCmpxNltF32,
  kVCmpxTruF32,
  kVCmpxFF64,
  kVCmpxLtF64,
  kVCmpxEqF64,
  kVCmpxLeF64,
  kVCmpxGtF64,
  kVCmpxLgF64,
  kVCmpxGeF64,
  kVCmpxOF64,
  kVCmpxUF64,
  kVCmpxNgeF64,
  kVCmpxNlgF64,
  kVCmpxNgtF64,
  kVCmpxNleF64,
  kVCmpxNeqF64,
  kVCmpxNltF64,
  kVCmpxTruF64,
  kVCmpxClassF16,
  kVCmpxClassF32,
  kVCmpxClassF64,
  kVCmpEqI32,
  kVCmpNeI32,
  kVCmpLtI32,
  kVCmpLeI32,
  kVCmpGtI32,
  kVCmpGeI32,
  kVCmpEqU32,
  kVCmpNeU32,
  kVCmpLtU32,
  kVCmpLeU32,
  kVCmpGtU32,
  kVCmpGeU32,
  kVCmpFI64,
  kVCmpLtI64,
  kVCmpEqI64,
  kVCmpLeI64,
  kVCmpGtI64,
  kVCmpNeI64,
  kVCmpGeI64,
  kVCmpTI64,
  kVCmpFU64,
  kVCmpLtU64,
  kVCmpEqU64,
  kVCmpLeU64,
  kVCmpGtU64,
  kVCmpNeU64,
  kVCmpGeU64,
  kVCmpTU64,
  kVCmpxFI32,
  kVCmpxLtI32,
  kVCmpxEqI32,
  kVCmpxLeI32,
  kVCmpxGtI32,
  kVCmpxNeI32,
  kVCmpxGeI32,
  kVCmpxTI32,
  kVCmpxFU32,
  kVCmpxLtU32,
  kVCmpxEqU32,
  kVCmpxLeU32,
  kVCmpxGtU32,
  kVCmpxNeU32,
  kVCmpxGeU32,
  kVCmpxTU32,
  kVCmpxFI64,
  kVCmpxLtI64,
  kVCmpxEqI64,
  kVCmpxLeI64,
  kVCmpxGtI64,
  kVCmpxNeI64,
  kVCmpxGeI64,
  kVCmpxTI64,
  kVCmpxFU64,
  kVCmpxLtU64,
  kVCmpxEqU64,
  kVCmpxLeU64,
  kVCmpxGtU64,
  kVCmpxNeU64,
  kVCmpxGeU64,
  kVCmpxTU64,
  kSAddU32,
  kSAddcU32,
  kSSubU32,
  kSSubbU32,
  kSMinI32,
  kSMinU32,
  kSMaxI32,
  kSMaxU32,
  kSMulI32,
  kSMulHiU32,
  kSMulHiI32,
  kSLshl1AddU32,
  kSLshl2AddU32,
  kSLshl3AddU32,
  kSLshl4AddU32,
  kSPackLlB32B16,
  kSPackLhB32B16,
  kSPackHhB32B16,
  kSCselectB32,
  kSCselectB64,
  kSAbsdiffI32,
  kSBfeU32,
  kSBfeI32,
  kSBfeU64,
  kSBfeI64,
  kSLshlB32,
  kSLshlB64,
  kSLshrB32,
  kSLshrB64,
  kSAshrI32,
  kSAshrI64,
  kSBfmB32,
  kSBfmB64,
  kSAndB32,
  kSAndn2B32,
  kSNandB32,
  kSAndB64,
  kSAndn2B64,
  kSNandB64,
  kSOrB32,
  kSOrn2B32,
  kSNorB32,
  kSOrB64,
  kSOrn2B64,
  kSNorB64,
  kSXorB32,
  kSXnorB32,
  kSXorB64,
  kSXnorB64,
  kSCmpEqI32,
  kSCmpLgI32,
  kSCmpGtI32,
  kSCmpGeI32,
  kSCmpLtI32,
  kSCmpLeI32,
  kSCmpEqU32,
  kSCmpLgU32,
  kSCmpGtU32,
  kSCmpGeU32,
  kSCmpLtU32,
  kSCmpLeU32,
  kSCmpEqU64,
  kSCmpLgU64,
  kSBitcmp0B32,
  kSBitcmp1B32,
  kSBitcmp0B64,
  kSBitcmp1B64,
  kSLoadDword,
  kSLoadDwordX2,
  kSStoreDword,
  kVCndmaskB32,
  kVAddU32,
  kVAddCoU32,
  kVAddcCoU32,
  kVAddF16,
  kVAddF32,
  kVSubF16,
  kVSubF32,
  kVMulF16,
  kVMulF32,
  kVSubU32,
  kVSubCoU32,
  kVSubbCoU32,
  kVSubRevU32,
  kVSubRevCoU32,
  kVSubbrevCoU32,
  kVMinF16,
  kVMinF32,
  kVMaxF16,
  kVMaxF32,
  kVMinI32,
  kVMaxI32,
  kVMinU32,
  kVMaxU32,
  kVAddF64,
  kVMulF64,
  kVMinF64,
  kVMaxF64,
  kVLshrRevB32,
  kVAshrRevI32,
  kVLshlRevB32,
  kVWritelaneB32,
  kVAndB32,
  kVOrB32,
  kVXorB32,
  kFlatLoadUByte,
  kFlatLoadUByteD16,
  kFlatLoadUByteD16Hi,
  kFlatLoadSByte,
  kFlatLoadSByteD16,
  kFlatLoadSByteD16Hi,
  kFlatLoadUShort,
  kFlatLoadShortD16,
  kFlatLoadShortD16Hi,
  kFlatLoadSShort,
  kFlatLoadDword,
  kFlatLoadDwordX2,
  kFlatLoadDwordX3,
  kFlatLoadDwordX4,
  kFlatStoreByte,
  kFlatStoreByteD16Hi,
  kFlatStoreShort,
  kFlatStoreShortD16Hi,
  kFlatStoreDword,
  kFlatStoreDwordX2,
  kFlatStoreDwordX3,
  kFlatStoreDwordX4,
  kGlobalLoadUByte,
  kGlobalLoadUByteD16,
  kGlobalLoadUByteD16Hi,
  kGlobalLoadSByte,
  kGlobalLoadSByteD16,
  kGlobalLoadSByteD16Hi,
  kGlobalLoadUShort,
  kGlobalLoadShortD16,
  kGlobalLoadShortD16Hi,
  kGlobalLoadSShort,
  kGlobalLoadDword,
  kGlobalLoadDwordX2,
  kGlobalLoadDwordX3,
  kGlobalLoadDwordX4,
  kGlobalStoreByte,
  kGlobalStoreByteD16Hi,
  kGlobalStoreShort,
  kGlobalStoreShortD16Hi,
  kGlobalStoreDword,
  kGlobalStoreDwordX2,
  kGlobalStoreDwordX3,
  kGlobalStoreDwordX4,
  kDsNop,
  kDsWriteB32,
  kDsReadB32,
  kDsSwizzleB32,
  kDsPermuteB32,
  kDsBpermuteB32,
  kDsAddU32,
  kDsSubU32,
  kDsRsubU32,
  kDsIncU32,
  kDsDecU32,
  kDsMinI32,
  kDsMaxI32,
  kDsMinU32,
  kDsMaxU32,
  kDsAndB32,
  kDsOrB32,
  kDsXorB32,
  kDsMskorB32,
  kDsCmpstB32,
  kDsCmpstF32,
  kDsAddF32,
  kDsMinF32,
  kDsMaxF32,
  kDsPkAddF16,
  kDsPkAddBf16,
  kDsWriteAddTidB32,
  kDsConsume,
  kDsAppend,
  kDsWriteB8,
  kDsWriteB16,
  kDsWriteB8D16Hi,
  kDsWriteB16D16Hi,
  kDsWriteB64,
  kDsWriteB96,
  kDsWriteB128,
  kDsWrite2B32,
  kDsWrite2St64B32,
  kDsWrite2B64,
  kDsWrite2St64B64,
  kDsReadB64,
  kDsReadB96,
  kDsReadB128,
  kDsReadAddTidB32,
  kDsRead2B32,
  kDsRead2St64B32,
  kDsRead2B64,
  kDsRead2St64B64,
  kDsWrxchg2RtnB32,
  kDsWrxchg2St64RtnB32,
  kDsWrxchg2RtnB64,
  kDsWrxchg2St64RtnB64,
  kDsReadI8,
  kDsReadU8,
  kDsReadI16,
  kDsReadU16,
  kDsReadU8D16,
  kDsReadU8D16Hi,
  kDsReadI8D16,
  kDsReadI8D16Hi,
  kDsReadU16D16,
  kDsReadU16D16Hi,
  kDsAddU64,
  kDsSubU64,
  kDsRsubU64,
  kDsIncU64,
  kDsDecU64,
  kDsMinI64,
  kDsMaxI64,
  kDsMinU64,
  kDsMaxU64,
  kDsAndB64,
  kDsOrB64,
  kDsXorB64,
  kDsMskorB64,
  kDsCmpstB64,
  kDsCmpstF64,
  kDsAddF64,
  kDsMinF64,
  kDsMaxF64,
  kDsAddRtnU32,
  kDsSubRtnU32,
  kDsRsubRtnU32,
  kDsIncRtnU32,
  kDsDecRtnU32,
  kDsMinRtnI32,
  kDsMaxRtnI32,
  kDsMinRtnU32,
  kDsMaxRtnU32,
  kDsAndRtnB32,
  kDsOrRtnB32,
  kDsXorRtnB32,
  kDsMskorRtnB32,
  kDsWrxchgRtnB32,
  kDsCmpstRtnB32,
  kDsCmpstRtnF32,
  kDsWrapRtnB32,
  kDsAddRtnF32,
  kDsMinRtnF32,
  kDsMaxRtnF32,
  kDsPkAddRtnF16,
  kDsPkAddRtnBf16,
  kDsAddRtnU64,
  kDsSubRtnU64,
  kDsRsubRtnU64,
  kDsIncRtnU64,
  kDsDecRtnU64,
  kDsMinRtnI64,
  kDsMaxRtnI64,
  kDsMinRtnU64,
  kDsMaxRtnU64,
  kDsAndRtnB64,
  kDsOrRtnB64,
  kDsXorRtnB64,
  kDsMskorRtnB64,
  kDsWrxchgRtnB64,
  kDsCmpstRtnB64,
  kDsCmpstRtnF64,
  kDsCondxchg32RtnB64,
  kDsAddRtnF64,
  kDsMinRtnF64,
  kDsMaxRtnF64,
  kGlobalAtomicSwap,
  kGlobalAtomicCmpSwap,
  kGlobalAtomicAdd,
  kGlobalAtomicSub,
  kGlobalAtomicSMin,
  kGlobalAtomicUMin,
  kGlobalAtomicSMax,
  kGlobalAtomicUMax,
  kGlobalAtomicAnd,
  kGlobalAtomicOr,
  kGlobalAtomicXor,
  kGlobalAtomicInc,
  kGlobalAtomicDec,
  kGlobalAtomicAddF32,
  kGlobalAtomicPkAddF16,
  kGlobalAtomicAddF64,
  kGlobalAtomicMinF64,
  kGlobalAtomicMaxF64,
  kGlobalAtomicPkAddBf16,
  kGlobalAtomicSwapX2,
  kGlobalAtomicCmpSwapX2,
  kGlobalAtomicAddX2,
  kGlobalAtomicSubX2,
  kGlobalAtomicSMinX2,
  kGlobalAtomicUMinX2,
  kGlobalAtomicSMaxX2,
  kGlobalAtomicUMaxX2,
  kGlobalAtomicAndX2,
  kGlobalAtomicOrX2,
  kGlobalAtomicXorX2,
  kGlobalAtomicIncX2,
  kGlobalAtomicDecX2,
  kSBranch,
  kSCbranchScc0,
  kSCbranchScc1,
  kSCbranchVccz,
  kSCbranchVccnz,
  kSCbranchExecz,
  kSCbranchExecnz,
  kVAccvgprReadB32,
  kVAccvgprWriteB32,
  kVAccvgprMovB32,
  kVMfmaF32_4x4x1_16bF32,
  kVMfmaF32_16x16x4F32,
};

struct CompiledInstruction {
  static constexpr std::uint8_t kFlagIsGlobal = 1u << 0;
  static constexpr std::uint8_t kFlagIsLoad = 1u << 1;
  static constexpr std::uint8_t kFlagIsSignedLoad = 1u << 2;
  static constexpr std::uint8_t kFlagHasReturn = 1u << 3;

  CompiledOpcode opcode = CompiledOpcode::kSEndpgm;
  std::array<InstructionOperand, DecodedInstruction::kMaxOperands> operands{};
  std::uint8_t operand_count = 0;
  std::uint8_t flags = 0;
  std::uint8_t register_dword_count = 0;
  std::uint8_t element_size_bytes = 0;
  std::uint8_t memory_dword_count = 0;
  std::uint8_t data_dword_count = 0;

  bool IsGlobal() const { return (flags & kFlagIsGlobal) != 0; }
  bool IsLoad() const { return (flags & kFlagIsLoad) != 0; }
  bool IsSignedLoad() const { return (flags & kFlagIsSignedLoad) != 0; }
  bool HasReturn() const { return (flags & kFlagHasReturn) != 0; }
};

class Gfx950Interpreter {
 public:
  bool Supports(std::string_view opcode) const;
  bool CompileProgram(std::span<const DecodedInstruction> program,
                      std::vector<CompiledInstruction>* compiled_program,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const DecodedInstruction> program,
                      WaveExecutionState* state,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const DecodedInstruction> program,
                      WaveExecutionState* state,
                      ExecutionMemory* memory,
                      std::string* error_message) const;
  bool ExecuteProgram(std::span<const CompiledInstruction> program,
                      WaveExecutionState* state,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const CompiledInstruction> program,
                      WaveExecutionState* state,
                      ExecutionMemory* memory,
                      std::string* error_message) const;
  bool ExecuteProgramUntilYield(std::span<const DecodedInstruction> program,
                                WaveExecutionState* state,
                                ExecutionMemory* memory,
                                const WorkgroupExecutionContext* workgroup,
                                ProgramRunState* run_state,
                                std::string* error_message) const;
  bool ExecuteProgramUntilYield(std::span<const CompiledInstruction> program,
                                WaveExecutionState* state,
                                ExecutionMemory* memory,
                                const WorkgroupExecutionContext* workgroup,
                                ProgramRunState* run_state,
                                std::string* error_message) const;

 private:
  bool CompileInstruction(const DecodedInstruction& instruction,
                          CompiledInstruction* compiled_instruction,
                          std::string* error_message) const;
  bool ExecuteInstruction(const DecodedInstruction& instruction,
                          WaveExecutionState* state,
                          ExecutionMemory* memory,
                          const WorkgroupExecutionContext* workgroup,
                          bool* pc_was_updated,
                          bool* wave_yielded,
                          std::string* error_message) const;
  bool ExecuteInstruction(const CompiledInstruction& instruction,
                          WaveExecutionState* state,
                          ExecutionMemory* memory,
                          const WorkgroupExecutionContext* workgroup,
                          bool* pc_was_updated,
                          bool* wave_yielded,
                          std::string* error_message) const;

  bool ExecuteScalarMove(const DecodedInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteScalarMove(const CompiledInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteExecMaskOp(const DecodedInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteExecMaskOp(const CompiledInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteScalarBinary(const DecodedInstruction& instruction,
                           WaveExecutionState* state,
                           std::string* error_message) const;
  bool ExecuteScalarBinary(const CompiledInstruction& instruction,
                           WaveExecutionState* state,
                           std::string* error_message) const;
  bool ExecuteScalarCompare(const DecodedInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteScalarCompare(const CompiledInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteScalarMemory(const DecodedInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteScalarMemory(const CompiledInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteVectorMove(const DecodedInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteVectorMove(const CompiledInstruction& instruction,
                         WaveExecutionState* state,
                         std::string* error_message) const;
  bool ExecuteVectorToScalar(const DecodedInstruction& instruction,
                             WaveExecutionState* state,
                             std::string* error_message) const;
  bool ExecuteVectorToScalar(const CompiledInstruction& instruction,
                             WaveExecutionState* state,
                             std::string* error_message) const;
  bool ExecuteVectorUnary(const DecodedInstruction& instruction,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool ExecuteVectorUnary(const CompiledInstruction& instruction,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool ExecuteVectorBinary(const DecodedInstruction& instruction,
                           WaveExecutionState* state,
                           std::string* error_message) const;
  bool ExecuteVectorBinary(const CompiledInstruction& instruction,
                           WaveExecutionState* state,
                           std::string* error_message) const;
  bool ExecuteVectorTernary(const DecodedInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteVectorTernary(const CompiledInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteVectorCompare(const DecodedInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteVectorCompare(const CompiledInstruction& instruction,
                            WaveExecutionState* state,
                            std::string* error_message) const;
  bool ExecuteVectorMemory(const DecodedInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteVectorMemory(const CompiledInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteDsMemory(const DecodedInstruction& instruction,
                       WaveExecutionState* state,
                       const WorkgroupExecutionContext* workgroup,
                       std::string* error_message) const;
  bool ExecuteDsMemory(const CompiledInstruction& instruction,
                       WaveExecutionState* state,
                       const WorkgroupExecutionContext* workgroup,
                       std::string* error_message) const;
  bool ExecuteGlobalAtomic(const DecodedInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteGlobalAtomic(const CompiledInstruction& instruction,
                           WaveExecutionState* state,
                           ExecutionMemory* memory,
                           std::string* error_message) const;
  bool ExecuteBranch(const DecodedInstruction& instruction,
                     WaveExecutionState* state,
                     bool* pc_was_updated,
                     std::string* error_message) const;
  bool ExecuteBranch(const CompiledInstruction& instruction,
                     WaveExecutionState* state,
                     bool* pc_was_updated,
                     std::string* error_message) const;
  bool ExecuteBarrier(const DecodedInstruction& instruction,
                      WaveExecutionState* state,
                      const WorkgroupExecutionContext* workgroup,
                      bool* wave_yielded,
                      std::string* error_message) const;
  bool ExecuteBarrier(const CompiledInstruction& instruction,
                      WaveExecutionState* state,
                      const WorkgroupExecutionContext* workgroup,
                      bool* wave_yielded,
                      std::string* error_message) const;
  bool ExecuteAccvgprMove(const DecodedInstruction& instruction,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool ExecuteAccvgprMove(const CompiledInstruction& instruction,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool ExecuteMfma(const DecodedInstruction& instruction,
                   WaveExecutionState* state,
                   std::string* error_message) const;
  bool ExecuteMfma(const CompiledInstruction& instruction,
                   WaveExecutionState* state,
                   std::string* error_message) const;

  bool ValidateOperandCount(const DecodedInstruction& instruction,
                            std::uint8_t expected_operands,
                            std::string* error_message) const;
  bool ValidateOperandCount(const CompiledInstruction& instruction,
                            std::uint8_t expected_operands,
                            std::string* error_message) const;
  std::uint32_t ReadScalarOperand(const InstructionOperand& operand,
                                  const WaveExecutionState& state,
                                  std::string* error_message) const;
  std::uint64_t ReadScalarPairOperand(const InstructionOperand& operand,
                                      const WaveExecutionState& state,
                                      std::string* error_message) const;
  std::uint32_t ReadVectorOperand(const InstructionOperand& operand,
                                  const WaveExecutionState& state,
                                  std::size_t lane_index,
                                  std::string* error_message) const;
  bool ReadScalarAddressOperand(const InstructionOperand& operand,
                                const WaveExecutionState& state,
                                std::uint64_t* value,
                                std::string* error_message) const;
  bool ReadVectorAddressOperand(const InstructionOperand& operand,
                                const WaveExecutionState& state,
                                std::size_t lane_index,
                                std::uint64_t* value,
                                std::string* error_message) const;
  bool ResolveVectorMemoryAddress(const InstructionOperand& address_operand,
                                  const InstructionOperand* scalar_base_operand,
                                  std::int32_t signed_offset,
                                  const WaveExecutionState& state,
                                  std::size_t lane_index,
                                  std::uint64_t* address,
                                  std::string* error_message) const;
  bool WriteScalarOperand(const InstructionOperand& operand,
                          std::uint32_t value,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool WriteScalarPairOperand(const InstructionOperand& operand,
                              std::uint64_t value,
                              WaveExecutionState* state,
                              std::string* error_message) const;
  bool WriteVectorOperand(const InstructionOperand& operand,
                          std::size_t lane_index,
                          std::uint32_t value,
                          WaveExecutionState* state,
                          std::string* error_message) const;
  bool WriteAccvgprOperand(const InstructionOperand& operand,
                           std::size_t lane_index,
                           std::uint32_t value,
                           WaveExecutionState* state,
                           std::string* error_message) const;
  bool ApplyRelativeBranch(std::int32_t delta_in_instructions,
                           WaveExecutionState* state,
                           bool* pc_was_updated,
                           std::string* error_message) const;
  bool ReadMemoryU32(ExecutionMemory* memory,
                     std::uint64_t address,
                     std::uint32_t* value,
                     std::string* error_message) const;
  bool ReadMemoryU16(ExecutionMemory* memory,
                     std::uint64_t address,
                     std::uint16_t* value,
                     std::string* error_message) const;
  bool ReadMemoryU8(ExecutionMemory* memory,
                    std::uint64_t address,
                    std::uint8_t* value,
                    std::string* error_message) const;
  bool WriteMemoryU16(ExecutionMemory* memory,
                      std::uint64_t address,
                      std::uint16_t value,
                      std::string* error_message) const;
  bool WriteMemoryU8(ExecutionMemory* memory,
                     std::uint64_t address,
                     std::uint8_t value,
                     std::string* error_message) const;
  bool WriteMemoryU32(ExecutionMemory* memory,
                      std::uint64_t address,
                      std::uint32_t value,
                      std::string* error_message) const;
};

}  // namespace mirage::sim::isa

#endif  // MIRAGE_SIM_ISA_GFX950_INTERPRETER_ARCH_H_
